spring.application.name=Lab

spring.datasource.url=jdbc:postgresql://localhost:5432/jordan123
spring.datasource.username=jordan123
spring.datasource.password=jordan123

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true